### ISSUE TITLE
bundle a simple httpd?

### ISSUE THREAD

**Issue by slingamn** [ergochat/ergo#1033]
Suggestion from @prawnsalad: provide an httpd that can serve static files, in particular Kiwi.

I have some misgivings about this relative to just recommending nginx but it's worth thinking about.

**Comment by DanielOaks** [comment]
Hmm. So #1008 and #71 is a similar thing. Serving an API endpoint at `localhost:<adminport>/api/` and at `localhost:<adminport>/` serving a config editor (and/or eventually a general admin dashboard).

If we find a nice way to do one then we can do the other as well. Honestly, the only thing we'd need in the config file is just a note of the root folder and the port to spin up the httpd on. So long as there's a client that runs entirely in js on the client-side using static files, can connect with websockets, and that we can stick a config file into then it'd work. Is there anything besides kiwi that also satisfies those requirements?

I'm not 100% sure about bundling this with ora in our source tree and all by default. Both because it'd probably cause a loooot of support headaches for kiwi and because, well, it makes me feel icky. But with one release, alongside the normal Oragono build we could include an oragono+kiwi build and see how it goes? And if people find it useful, we could look at doing it more in the future or building more automated ways to create the two builds for us (along with ones for any other client that satisfies the above requirements and works well).

Prawn also mentioned possibly just serving this on the irc port directly and doing the muxing/multiplexing style thing that iirc one server out there does... I seem to remember Chary doing something like this for their websocket serving, maaaybe? We could look at that but I really don't want us to be modifying the served content ourselves in any way as much as we can. Leaving it alone and just subbing in a config file or something at build time is the most we really want to get involved with client config and dynamic stuff right now I reckon.

**Comment by DanielOaks** [comment]
Oh, another point re just muxing a client onto `:6667`/`:6697`, if we do want to explore that path (muxing makes me a little nervous but it's probably not too warranted). We need to think about whether to serve a client on there, or serve websockets on there instead. Could do either, serving websockets on the same port feels more protocol-happy if the rest of the irc servers haven't agreed on a standardised irc-websocket port yet.

**Comment by prawnsalad** [comment]
fwiw, ZNC + KiwiBNC both serve http+irc endpoints on the same port as it makes setup a lot easier for end users.

While I personally wouldn't mind if Kiwi is bundled with software (this was one of the driving factors behind having the config file separate + configurable as it is, so that software can config the client on the fly), IMO it would make better separation and be less forceful if you included a "setup_kiwi_web_client.sh" script or something that admins can run themselves rather than include it in your source directly. The script downloading kiwi from somewhere, extracting+applying any config changes. This would also let you include any other client-side clients when they appear in future without fuss.

**Comment by DanielOaks** [comment]
Hmm, cross-platform is good so including just a shell script seems a bit weird. I could see having a `/client/` directory that contains a few `setup-<client>-<platform>.ext` scripts, our build script could include the right scripts in the right platform builds. It wouldn't be much work to ask users to uncomment a section in the config file at the end of the setup script.

**Comment by trobotham** [comment]
It would probably be best to create a docker container which either has both bundled into a single container or a docker-compose file which bundles 2 containers together. This would allow for a bundled ease-of-setup for someone who wants something simple to setup for a bundled chat/irc solution with good integration or just for a general tech demo. You can utilize [LinuxServer's SWAG](https://docs.linuxserver.io/images/docker-swag) (probably preferred) for the reverse proxy/web gateway or even [Caddy](https://hub.docker.com/_/caddy?tab=description). You may also find https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ of interest.

**Comment by slingamn** [comment]
Closing in favor of #1862.
