### ISSUE TITLE
Implement SCRAM-SHA-256

### ISSUE THREAD

**Issue by DanielOaks** [ergochat/ergo#175]
This is something I wanna do as per https://tools.ietf.org/html/rfc7677 and it being recommended by IRCv3. Keep in mind https://github.com/ircv3/ircv3-specifications/pull/326

**Comment by slingamn** [comment]
This will help: https://github.com/jesopo/bitbot/blob/master/modules/sasl/scram.py

**Comment by slingamn** [comment]
This implementation is officially endorsed by Mongo (heh heh): https://github.com/xdg-go/scram

**Comment by slingamn** [comment]
I've decided this isn't a priority for me, but I'm leaving the "help wanted" tag up because I'm definitely interested in outside PRs that add this.

**Comment by Mikaela** [comment]
Considering how recent Charybdis/fork+Atheme support this mechanism, this may be a offered mechanism downgrade for networks migrating to Ergo.

I think e.g. WeeChat lets you specify only one mechanism to be used for SASL authentication instead of preferred mechanism list and it recently added support for this.

Another argument for supporting the mechanism is that Ergo is leading in all other IRCv3 implementation and testing SCRAM has to be done separately somewhere else.

**Comment by slingamn** [comment]
>Another argument for supporting the mechanism is that Ergo is leading in all other IRCv3 implementation and testing SCRAM has to be done separately somewhere else.

I like this point!

I have been avoiding this because it is somewhat difficult to implement: it's not just a matter of adding the algorithm, we also have to bump the CredentialsVersion and handle re-hashing passwords as users log back in:

https://github.com/ergochat/ergo/blob/97d1786378c843f25a07e25e83c1b4c8ddadbd26/irc/accounts.go#L1894-L1902

since a bcrypt hash is not enough to support this mechanism, we need to obtain the plaintext password (temporarily) and hash it with PBKDF2.

**Comment by Mikaela** [comment]
I have seen SASL SCRAM also been suggested as a mitigation towards not leaking plaintext password to a typosquatting network recently.

**Comment by slingamn** [comment]
https://github.com/xdg-go/scram adds about a megabyte to the binary size on linux/amd64, mostly due to this:

https://github.com/xdg-go/stringprep

It's unclear whether we can get away with commenting out the uses of `stringprep`. RFC 5802 says:

>Note that implementations MUST either implement SASLprep or disallow use of non US-ASCII Unicode codepoints in "str".

which would seemingly apply to both usernames and passwords.

**Comment by slingamn** [comment]
Proposal:

1. Fork xdg-go/scram, remove stringprep
2. SCRAM is not supported for account names with non-US-ASCII characters; we'll send `ERR_SASLFAIL` at some point in the process. Compare #1718.
3. Going forward, non-US-ASCII characters are disallowed by `validatePassphrase`

**Comment by Mikaela** [comment]
> SCRAM is not supported for account names with non-US-ASCII characters; we'll send ERR_SASLFAIL at some point in the process. Compare consider making 'ascii' the default/recommended casefolding #1718.

I am not sure on this point as it seems very anglocentric and I think it's in clash with

> ('precis' would remain fully supported in the codebase, especially because operators can't safely switch between casefoldings, at the risk of making account or channel registrations unusable.)

from https://github.com/ergochat/ergo/issues/1718#issue-931191330.

**Comment by slingamn** [comment]
From discussion, we're going to reimplement stringprep, relying on PRECIS to enforce most of the constraints. If an account name passes PRECIS, only a few more steps should be necessary:

1. Remove 20 or so prohibited runes: https://github.com/xdg-go/stringprep/blob/4fcaaf19bc2a8e388ba275a82eb34c29abcd0bc9/tables.go#L411
2. Normalize some space characters (these are likely prohibited by PRECIS anyway): https://github.com/xdg-go/stringprep/blob/4fcaaf19bc2a8e388ba275a82eb34c29abcd0bc9/saslprep.go#L3
3. Apply NFKC: https://github.com/xdg-go/stringprep/blob/4fcaaf19bc2a8e388ba275a82eb34c29abcd0bc9/profile.go#L36

PRECIS doesn't apply to passwords, but we can probably just get away with violating the spec for the (hopefully small and atypical) set of Unicode passphrases that don't pass bidi or similar.

**Comment by Neustradamus** [comment]
@slingamn: Good job!
- https://github.com/ergochat/ergo/pull/1764

Linked to:
- https://github.com/scram-sasl/info/issues/1
