### ISSUE TITLE
"That account name was registered previously and can't be reused" - why?

### ISSUE THREAD

**Issue by TETYYS** [ergochat/ergo#1821]
Does that mean unregistering doesn't really unregister an account?

**Comment by TETYYS** [comment]
I deleted the key at account.unregistered manually and I don't see any strange side-effects

**Comment by slingamn** [comment]
Short answer: you can use `NS ERASE` for this, but you shouldn't.

Long answer: in its default/recommended configuration, Ergo implements a model of identity inspired by Reddit. In short:

1. Registered nicknames (account names) are trusted data; no one other than the account owner can use them
2. Users are strongly encouraged to use their registered account name, and no other name, as their public identity (`force-nick-equals-account`)
3. If someone unregisters an account, the name remains reserved so that no one else can register it and impersonate the original user. All account/user data is deleted, in the interests of user privacy --- Ergo only retains the record that the name was once registered (the `account.unregistered` key you deleted)
4. Operators can remove accounts completely using `NS ERASE`, but this isn't recommended

See #793 and the linked ircv3-specifications issue for more context. See #1545 for a previous attempt to mitigate confusion on this subject.

What was your use case for unregistering the account?

**Comment by TETYYS** [comment]
That makes sense, my use case was changing account name and since there's no command to this I unregister and register
