### ISSUE TITLE
Go indexing servers don't pick up 2.x ergo versions

### ISSUE THREAD

**Issue by yurivict** [ergochat/ergo#1841]
I use this script to retrieve package versions as known to Go indexing servers:
```
$ cat go-retrieve-all-packages.sh
#!/bin/sh

SINCE=$1 # like 2021-08-01T00:00:00Z

while [ -n "${SINCE}" ]; do

	# download
	echo "downloading SINCE=${SINCE}"
	wget "https://index.golang.org/index?limit=2000&since=${SINCE}" -q -O output-${SINCE}.json

	# get last since
	SINCE_NEW=`tail -1 output-${SINCE}.json | sed -e 's|.*"Timestamp":"||; s|".*||'`

	# EOF?
	if [ "${SINCE_NEW}" = "${SINCE}" ] || [ -z "${SINCE_NEW}" ]; then
		echo "=== End of project list reached @ ${SINCE} ==="
		exit 0
	else
		SINCE=${SINCE_NEW}
	fi
done
```

Invocation:
```
./go-retrieve-all-packages.sh 2021-11-01T00:00:00Z
```

For ```ergo``` grep through the retrieved records shows this:
```
$ grep ergoch output-2021-11-*
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211114042415-9a007d07f8c6","Timestamp":"2021-11-16T07:38:39.178441Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211029090401-41089b0e1671","Timestamp":"2021-11-16T07:38:39.262872Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211029022545-b478e93c11ee","Timestamp":"2021-11-16T07:38:39.422618Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211004032928-1b55520006f8","Timestamp":"2021-11-16T07:38:39.568505Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211102032532-ea1678ec8f3a","Timestamp":"2021-11-16T07:38:39.959122Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211114051119-c70e518eed89","Timestamp":"2021-11-16T07:38:41.16472Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211111173217-3d4170ef98e7","Timestamp":"2021-11-16T07:38:41.611801Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211031223432-84a5b83eb1ca","Timestamp":"2021-11-16T07:38:42.331204Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211015050827-404bf6c2a064","Timestamp":"2021-11-16T07:38:44.346583Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211114021646-7ee071240125","Timestamp":"2021-11-16T07:38:44.416801Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211107183218-dc75b24d23e6","Timestamp":"2021-11-16T07:38:44.782778Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211108082045-4a3ac617a538","Timestamp":"2021-11-16T07:38:45.686275Z"}
output-2021-11-16T07:36:08.508766Z.json:{"Path":"github.com/ergochat/ergo","Version":"v1.2.1-0.20211114181258-92f6bf2d0392","Timestamp":"2021-11-16T07:38:53.901528Z"}
output-2021-11-20T00:01:52.205739Z.json:{"Path":"github.com/ergochat/irc-go","Version":"v0.0.0-20200311142257-57fd157327ac","Timestamp":"2021-11-20T02:39:35.43746Z"}
```

As a result the FreeBSD port (and others) can't retrieve all dependencies in a Go-standard way.

**Comment by DanielOaks** [comment]
Ah, yep this is likely the same thing that was happening in https://github.com/ergochat/ergo/issues/1630#issuecomment-828115477. Unfortunately Go defaults to 1.x.x tags when grabbing stuff from a repo, rather than the latest tags. To use 2.x and have Go continue to grab it we'd need to switch to another branch or repo or something like that, so the standard Go tools don't work in the expected way here (that's why we say clone the repo and go from there, because that should work).

I wonder whether just killing all the pre-2.0 tags could make Golang actually treat this properly?

**Comment by csmith** [comment]
> To use 2.x.x and have Go continue to grab it we'd need to switch to another branch or repo or something like that

As far as I know all you'd need to do is change the module name to `github.com/ergochat/ergo/v2`.

From https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher:

> Major branch: Update the go.mod file to include a /v3 at the end of the module path in the module directive (e.g., module github.com/my/module/v3). Update import statements within the module to also use /v3 (e.g., import "github.com/my/module/v3/mypkg"). Tag the release with v3.0.0.
> ...
>  Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).

Then anything trying to fetch github.com/ergochat/ergo/v2 as a go module will hit future v2.xxx tags as expected. (The current tags won't work because their go.mods incorrectly (implicitly) identify them as v1.)

This would require changing the build commands, imports, and possibly a couple of other small things, but wouldn't really be user-visible.

**Comment by yurivict** [comment]
> As far as I know all you'd need to do is change the module name to github.com/ergochat/ergo/v2

Exactly.

**Comment by slingamn** [comment]
Ah, yeah, this is worth considering, but we probably want to discourage people from importing ergo because nothing in ergo proper is API-stable. I'll think about what I want to do here.

I pulled in `github.com/ergochat/ergo/irc/utils` for [webircproxy](https://github.com/ergochat/webircproxy) by fetching the git hash I wanted. This worked, but is somewhat confusing:

https://github.com/ergochat/webircproxy/blob/1a9c7bcff3918cbd73cbb5817d03a080ed395efd/go.mod#L6

The `go.mod` line says `v1.2.1` but actually that hash (20d8d269ca1879753ffa0a7f63663d626357e183) is a 2.x version.

@yurivict are you packaging Ergo for FreeBSD? If so, you should use our in-tree vendored dependencies only. `make build` from a source tarball or a git checkout should build the project without needing to fetch anything.

**Comment by yurivict** [comment]
> are you packaging Ergo for FreeBSD? If so, you should use our in-tree vendored dependencies only. make build from a source tarball or a git checkout should build the project without needing to fetch anything.

I didn't know this. I removed dependencies from the port.

Thanks!

**Comment by slingamn** [comment]
I tried out this change. @csmith's instructions were accurate and very straightforward: you just change the `module` line in `go.mod` and then run:

```bash
git ls-files | grep go$ | xargs sed -i 's/github.com\/ergochat\/ergo\/irc/github.com\/ergochat\/ergo\/v2\/irc/g'
````

however, I decided against doing this. I think it's appropriate to have a roadblock against fetching ergochat/ergo packages with `go get`, because if you're doing that you're very likely doing something that's not recommended and will cause problems down the line.
