### ISSUE TITLE
Server side muting of leave/join messages in Histserv?

### ISSUE THREAD

**Issue by poVoq** [ergochat/ergo#1845]
I am aware that registered users can hide join/leave messages in histserv individually*, but for unregistered users and those using a webclient with build-in history support (Kiwiirc) it can be really annoying to have the back-log flooded with join/leave messages by someone with an unstable connection. As a result the history support becomes almost unusable when join/leave messages flood out real messages by a factor of 100/1.

*I also noticed that during the last database update this user-setting got reset somehow.

**Comment by slingamn** [comment]
Right, this was removed because it broke pagination (#1676).

I'll think about what to do here, this whole situation is a mess.

**Comment by slingamn** [comment]
OK, so, on the one hand, I regret this situation. On the other hand, if you look at the blow-by-blow of #1676, the upshot is that CHATHISTORY is a relatively low level API, and it's more important for us to have an implementation that is correct, fast, and reliable than to try to improve UX directly through implementation tweaks.

Ultimately the best place to fix this issue is going to be the client, not the server. Unfortunately the Kiwi maintainers don't seem very interested in CHATHISTORY anymore, or perhaps they have other priorities given their limited resources. [gamja](https://git.sr.ht/~emersion/gamja/) seems to be doing a much better job of keeping up with the spec, and it has support for collapsing historical joins and parts. For example, checking https://ergo.chat/gamja just now:

```
01:16:18 — 04:28:25 test has joined, tar_xvf, zaher, NiKaN, Ariadne, petteri, jwheare and test have quit
```
