### ISSUE TITLE
Running on concurrent connection larger than 2000

### ISSUE THREAD

**Issue by kingter-sutjiadi** [ergochat/ergo#1974]
hi guys

i'm using ergo for my chat service on mobile apps, but when it on 2000 concurrent connection the service become slowed down heavily, some user can connect after waiting 2-5 minutes, do i need to adjust config for handling this many connection.

lovin this projects so far 👍

**Comment by slingamn** [comment]
Thanks for the report! Some quick questions:

1. What version of Ergo is this?
2. Did you already adjust the maximum open file limit, either via the systemd unit file or some other mechanism? You can check the limit with `cat /proc/$(pgrep ergo)/limits` (substitute the actual PID in case of ambiguity)
3. Are all 2000 users on the same channel?
4. Do you see any bottlenecks in system-wide metrics under this workload, e.g. CPU or network? What kind of hardware are you using?

**Comment by slingamn** [comment]
I recommend upgrading to 2.10.0, although that probably won't have much effect on your immediate problem.

The open file limit looks OK (it looks like you're using the systemd unit file, which allows 1048576 open files).

2000 clients per channel is close to our estimated scalability limit:

https://github.com/ergochat/ergo/blob/master/docs/MANUAL.md#scalability

This is in part due to limitations of the IRC protocol itself (JOIN and QUIT need to be broadcast to all channel participants, causing an O(n^2) blowup in traffic).

However, there is still hope! Can you examine system metrics to see what resources Ergo is bottlenecking on? Given the specifications you described (2 GB of RAM and 2 CPU cores), I suspect you might be maxing out the CPU (you can see this in `top`) or the network card (you can see this in `iotop`). You should also check `journalctl --follow` for error loglines.

**Comment by kingter-sutjiadi** [comment]
hi this is the top 


![image](https://user-images.githubusercontent.com/52060866/174132145-ead06983-8b08-479e-b376-b3634e0ab52a.png)


currently i'm facing issue like this it won't log in to the irc, somehow it's already pass the peak. traffic, but still this thing occured

![image](https://user-images.githubusercontent.com/52060866/174132307-37e4c72c-6ceb-44a2-a0da-a0097d4e5019.png)

this is the journalctl follow
![image](https://user-images.githubusercontent.com/52060866/174132569-b4726dd1-a5d5-4785-aa5d-365afe4694e5.png)



anyway i want to ask about the CRON in the ergo system what do they actually do?

**Comment by kingter-sutjiadi** [comment]
do i need to restart the service  seems the service is currently froze

**Comment by tacerus** [comment]
Given your logrotate service is failing, I suggest to additionally check the disk usage using `df -h`.

**Comment by kingter-sutjiadi** [comment]
![image](https://user-images.githubusercontent.com/52060866/174133662-e8b0befa-4b62-4e05-88fd-a64f86584493.png)

**Comment by slingamn** [comment]
>do i need to restart the service seems the service is currently froze

Does it respond over loopback? Try `nc 127.0.0.1 6667` and then typing `CAP LS 302` and pressing enter.

You can also try sending it SIGHUP and watching the log output to see if it successfully rehashes. If it does rehash, then uncomment the `pprof-listener` line in the config, send SIGHUP again, and then get the output of this command: `curl http://127.0.0.1:6060/debug/pprof/goroutine?debug=2`

**Comment by kingter-sutjiadi** [comment]
Hi, i'm killing the process and re  start it again and somehow it works😅, 

Anw what SIGHUP do? And how is rehashing works?

**Comment by slingamn** [comment]
"Rehash" refers to reloading the configuration file. This can be done either via the IRC `REHASH` command (as an operator with sufficient privileges), or by sending Ergo a SIGHUP.

Please enable the `pprof-listener` as described above: that way if we see another apparent freeze, we can get more information about the cause.

**Comment by kingter-sutjiadi** [comment]
@slingamn  hi sry for catching up late

here's the curl result

![image](https://user-images.githubusercontent.com/52060866/174203275-61e3547a-e95f-48ee-a37a-6e35561cca47.png)


and this is the loopback respond

![image](https://user-images.githubusercontent.com/52060866/174203365-a13d7693-ab5c-4642-84a0-3beb09000dcb.png)

**Comment by slingamn** [comment]
The account registration throttle wouldn't affect that. It only restricts the creation of new accounts, not access to existing accounts.

It sounds like some kind of resource exhaustion is happening on your server? Next time it happens, log in and see if you can determine whether it's CPU, RAM, or network bandwidth being exhausted.

**Comment by kingter-sutjiadi** [comment]
if we're connecting using same nickname (only fill nickname) does it mean we access the existing account

![image](https://user-images.githubusercontent.com/52060866/174267518-498407a3-4ad7-4ba1-a78c-990952fdeb71.png)

**Comment by kingter-sutjiadi** [comment]
![image](https://user-images.githubusercontent.com/52060866/174269818-0e587152-a24e-443d-9758-9af55fd64b5a.png)

![image](https://user-images.githubusercontent.com/52060866/174269931-46508564-39da-4949-8da4-aadeea2bfd18.png)


 currently i'm facing another freeze, this is the iotop and top

**Comment by slingamn** [comment]
Do you have the curl response from the freeze? It's longer than will fit in a single screenshot, you should send it to a file with `>` and then put the file in a pastebin:

`curl http://127.0.0.1:6060/debug/pprof/goroutine?debug=2 > goroutine-stack-dump`

**Comment by slingamn** [comment]
>if we're connecting using same nickname (only fill nickname) does it mean we access the existing account

Only if you're logging into registered accounts with SASL. It's starting to sound like this might be a client issue?

The `CAP LS 302` test I described earlier should help isolate client issues. If the server is "frozen" with respect to outside connections, but responds immediately to `CAP LS 302` over local `nc`, then it's some kind of client or networking issue.

Did you check `journalctl` for errors? You can do `journalctl --since=-24h` and look for Ergo or firewall-related errors.

**Comment by kingter-sutjiadi** [comment]
hi @slingamn thank you finally i found the issue, i use HAProxy in front of the ergo service, when i check the proxy i realize some connection is stuck and hitting the maximum connection threshold, seems the ergo don't have any issues after all, but thank you for the insight debugging and stuffs, i'll close the issue now

**Comment by slingamn** [comment]
Thanks! Try upgrading to 2.10.0 when you get a chance :-)

https://github.com/ergochat/ergo/releases/tag/v2.10.0
