### ISSUE TITLE
Input line too long

### ISSUE THREAD

**Issue by kingter-sutjiadi** [ergochat/ergo#2075]
Hi one of my client got  this error from server when chat like this

<IRCMsg: from=beta-ergo.idn.media <IRCCmd: 417 args=timotius-leonardo,Input line too long>>

the client is iOS using swift-nio pod

what configuration do i need to change to be able to send the message

**Comment by slingamn** [comment]
Try setting `server.compatibility.allow-truncation` to `true`, then rehashing or restarting.

**Comment by slingamn** [comment]
What client is this exactly? The OS and the I/O framework aren't necessarily relevant, the issue is that the client is sending lines that violate the IRC protocol by being longer than 512 total bytes (not including tags). See here: https://modern.ircdocs.horse/#message-format

**Comment by kingter-sutjiadi** [comment]
hi thank you for the responses, sry for the late reply, can we increase the 512 total byte limit?

**Comment by slingamn** [comment]
Ergo already allows 4096 bytes of tag data. The body section and the tags section are counted separately, and the body section is limited to 512 bytes.

There is an Ergo configuration option to increase the body length limit (`server.max-line-len`) but it is very dangerous to change this value, since it breaks compatibility with mainstream clients. (The problem is this: a PRIVMSG sent from a modern client may ultimately need to be relayed to an older client that assumes a 512-byte limit on the total message size. Tags are not a problem here because such an older client does not support tags, so the tags section is dropped in its entirety.)

**Comment by kingter-sutjiadi** [comment]
thank you i'll close the issue @slingamn 🙏
