### ISSUE TITLE
ERGO Email Verification

### ISSUE THREAD

**Issue by Gallaxial** [ergochat/ergo#2076]
ERGO Email Verification thru SMTP

-NickServ- Could not dispatch registration e-mail: dial tcp 64.182.101.45:25: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I write the :: server: 192.168.5.202  not work it give  tcp 64.182.101.45:25  instead
its my own Email server! , BUG? , It not Work , I need to authenticate my users by Email !

**Comment by slingamn** [comment]
Sorry about the delay, I missed this somehow. We look up the MX record for the domain, then resolve the resulting name to an A or AAAA record and dial port 25 on that address. It sounds like your MX record is misconfigured so that it points (indirectly) to 64.182.101.45, when it should be pointing to 192.168.5.202? Are you able to receive email at this domain normally?

**Comment by Gallaxial** [comment]
Its a local ip on another computer, i do not need a mx

**Comment by slingamn** [comment]
You're sending an email to, e.g. `accountname@[11.22.33.44]` ? Apparently that's the syntax for sending to an IP address, but it's not recommended: https://www.serviceobjects.com/blog/ip-address-vs-domain-in-an-email-address/

**Comment by slingamn** [comment]
Just checking in, any update on this issue?
