### ISSUE TITLE
Force join / autojoin / sajoin new clients to a channel

### ISSUE THREAD

**Issue by adsr** [ergochat/ergo#2077]
Hello, is there a way to make new clients force join a channel on connect? Thank you.

**Comment by slingamn** [comment]
This was considered in the past, but deemed user-unfriendly:

https://github.com/ergochat/ergo/blob/eeb7c6cb917ee9fbe469cd110c8121082eb4d350/docs/INFO.md#rejected-features

@DanielOaks what are your feelings about this going forward? @adsr , what's your use case? (It is technically possible to implement this using a bot that parses snotices and issues a SAJOIN, but it is somewhat painful since we don't have machine-readable snotices yet.)

**Comment by adsr** [comment]
Understood. This is for a small community network with a single channel. Some members are not used to IRC (ex-Discord) so the less commands we require of them the better. It's currently running on InspIRCd which has a force-join feature.

Some sort of scripting API with hooks might also solve this.

**Comment by slingamn** [comment]
What clients are people typically using? Gamja and Kiwi let you suggest a channel to auto-join from the landing page, e.g.

https://ergo.chat/kiwi/

**Comment by DanielOaks** [comment]
@slingamn I don't think I feel super strongly about it, so long as the use case (small community servers) is mentioned as a comment nearby where you can set this channel.

**Comment by slingamn** [comment]
Implemented in #2079
