### ISSUE TITLE
question regarding multiline

### ISSUE THREAD

**Issue by terminaldweller** [ergochat/ergo#2152]
I'm having a bot dump some markdown into a channel on my networks.
Leading whitespaces are remove from the markdown code blocks. The bot also adds terminal color escape codes which ergo sometimes breaks in the middle on the escape sequence which ends up in garbled text.
My question is, is my understanding correct that this part is being handled by irc/utils/text.go?
Also, is there a config option that I can tweak to stop ergo from doing this behaviour?

**Comment by slingamn** [comment]
No, this is a client-side issue. The `SplitMessage` type does not do its own message splitting, it just keeps track of messages that were split by clients implementing [draft/multiline](https://ircv3.net/specs/extensions/multiline.html). This was an intentional decision of draft/multiline to leave all splitting up to the client. (It doesn't sound like you're implementing `draft/multiline` so this is probably irrelevant to your case.)

In Ergo's default/recommended configuration (`allow-truncation: false`), it won't even truncate oversized messages (which is typical for an ircd), it just rejects them.

I would try adding more logging on the client side to see what exactly is being sent to Ergo, and what code is splitting the messages. (What bot or framework is this?)

**Comment by terminaldweller** [comment]
It's [this](https://github.com/terminaldweller/milla).
Thanks for the answer. 
It could be [gric](https://github.com/lrstanley/girc).
It has to be girc or ergo since [chroma](https://github.com/alecthomas/chroma)'s output is as expected. somewhere after girc sends the text to ergo things go wrong.
thanks again.
I'll go look some more.
